### ISSUE TITLE
Potential issue with scrolling in OS X

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#123]
Scrollbars are hidden by default in OS X. This might mean some users don't realise that the left navigation continues below the fold - especially as the nav doesn't scroll when you scroll the main content area.

![image](https://user-images.githubusercontent.com/1590604/34782349-4f38486c-f620-11e7-8bdc-831a42aaf773.png)

One potential fix would be to make it so that when you scroll the main content area the nav scrolls with it until it reaches the end of the column.

**Comment by 36degrees** [comment]
Another potential fix would be to add a 'fade' to white at the bottom of the nav, which doesn't feel very 'GOV.UK', but might be worth trying.

We looked at this issue specifically with regard to code blocks in the tech docs template (https://github.com/alphagov/tech-docs-template/pull/10). The sidebar was less of an issue because it was being used to present a table of contents for the active page and scrolled to highlight the active section.

**Comment by nickcolley** [comment]
It's possible to style webkit scrollbars like so:

```
::-webkit-scrollbar {
  width: 10px;
}

::-webkit-scrollbar-track {
  background: white;
}

::-webkit-scrollbar-thumb {
    border-radius: 0px;
    border-left: 2px solid;
    border-right: 2px solid;
    border-color: white;
    background: grey;
}
```

Which ends up with:


<img width="1434" alt="screen shot 2018-01-10 at 17 09 18" src="https://user-images.githubusercontent.com/2445413/34785422-03db2548-f629-11e7-8c9e-907e5c023508.png">

Would need cross browser checking, since this probably is only an issue on OSX

**Comment by 36degrees** [comment]
Note that that will restyle scrollbars in Chrome on Windows to look like Mac OS scrollbars. Which is why we opted away from that solution in the tech docs template.

**Comment by nickcolley** [comment]
We could sniff for OSX and only show them on OSX, but that is getting pretty dodgy

**Comment by joelanman** [comment]
making chrome on windows scrollbars look like mac os doesnt sound so bad - are they still clearly usable?

**Comment by timpaul** [comment]
Yeah, I think at this stage we should wait until we see anything in user
research.

**Comment by nickcolley** [comment]
👍 will close for now
