### ISSUE TITLE
Decide on what the notification banner does or does not replace

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#1339]
## What

Make decision on the scope of the component (and what it does or does not replace)

## Why

Several working group members asked if there was a difference between the notification banner and other existing components within the design system. It could cause users to be confused or unclear about the use of the error summary, panel and notification banner components. 

We may find that the use of the notification banners makes some components obsolete.

## Who needs to know about this
Charlotte, Chris

## Further detail

- Especially worth looking into use cases of existing error summary and panel components.
- It may also be of interest to look into the relationship of each of the three components (error summary, notification banner and panel) across a user journey. This could address some comments raised about when to use each component, after which action it is highlighted to the user and for how long the notification appears.

We need to be clear about the use cases for:
- Error summary v error notification banner
- Panel v success notification banner
- Warning text v blue notification banner
- What a blue notification banner is for

We also need to decide what to do with the ['understand the impact of an emergency' pattern](https://design-system.service.gov.uk/patterns/understand-the-impact-of-an-emergency/).

## Done when

- [x] Identify risks and benefits with different options
- [x] Write down the use cases for each relevant component to show how they differ
- [x] Share with the team for discussion
- [x] Decide which component(s) to take forward

**Comment by christopherthomasdesign** [comment]
Decision on scope of component

Release a single notification banner component with different variants:
- information (blue)
- success (green)
- error (red)

The main reasons for this are:
* the variants have more in common than not
* alert behaviour  (role=alert and tabindex=0) doesn’t appear to be uniformly appropriate for red and green banners – it may be better make it clear that it’s configurable and why you would use it (perhaps seeing ‘alerts’ as a variant or section of the guidance)
* less duplication of code (although there remains the overlap with aspects of the error summary)
* the panel component was raised as being similar to the green banner but we think it meets a different need (a user reaching a significant outcome; more final and less temporary than a green banner)
* the working group approved the component in this form (albeit with a few suggestions of alternative configurations)

We shouldn't deprecate any existing components for now. Because we’re not 100% on the decision above. It’d be better to deprecate something further down the line and be confident about it than to deprecate something now and potentially need to revert our decision.

We should monitor behaviour to see if the new components result in confusion or misuse. We should set something up 3-6 months after we release 4.0.0 to review this.

Some of the thinking and debate about this is recorded in this [internal team doc](https://docs.google.com/document/d/1IVmbMxQ-HGTe8hdlQKenzAjQRL6N3YhigHM4Scdq14s/edit#).
