### ISSUE TITLE
Document / Implement Radio 'selected' value

### ISSUE THREAD

**Issue by andrewcharnley** [alphagov/govuk-design-system#1422]
Re: https://design-system.service.gov.uk/components/radios/

There's nothing here about pre-selecting a radio button on the above.

I attempted to use **selected:true** on one of the items as is the logic for the select component but this hasn't worked.

**Comment by andrewcharnley** [comment]
I'm doing both, the first is the wish of the UX, who I'll happily wind up tomorrow morning with that paragraph.

Thanks for the prompt reply all!

**Comment by hannalaakso** [comment]
@andrewcharnley I've [linked to your comment](https://github.com/alphagov/govuk-design-system/issues/1085#issuecomment-779292619) about missing the link for the Nunjucks options table as it's useful for us to know when we consider how to improve the presentation of this content to users. If you feel that I've misrepresented your comment in any way or you'd like to add anything else feel free to comment on that card.

As your issue was resolved I'm going to close this issue.
