### ISSUE TITLE
Accordion - it's not clear how section expanded is stored in session, and id has to be unique across the site

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#1443]
We store whether a user expanded a section, and use 'id' for that. It's not clear from the guidance that we do that, so it's unexpected, and that means its not clear that 'id' has to be unique across the whole site. There is some guidance in the nunjucks options but people might not see that.

In addition this means 'expanded' option may not work as expected - as the stored value will override it.

**Comment by 36degrees** [comment]
Is this the same as #1073?

**Comment by edwardhorsford** [comment]
I feel like the guidance (particularly the nunjucks option for `expanded`) could be clearer - it gave me confidence that there was an option to set the expanded state, but this didn't work, and doesn't work as expected.

I also feel like there should be a way to set the state on load - but this doesn't seem possible.

For prototyping, it's hard to test the `expanded` option. It didn't work when I tried it. 

I think because my process was:
* Copy the example from the design system
* Save
* Kit autorefreshes the page
* I possibly then tried the accordion to check it worked
* Add `expanded: true` to an option
* Kit autorefreshes the page
* Section is closed / expanded doesn't work

**Comment by edwardhorsford** [comment]
> Is this the same as #1073?

I originally raised this as I wanted to set an accordion section as expanded on load - and following the design system docs did not work. So whilst one reason for the issue might be about ID's, for me the issue is clarity around how the expanded state works / updating it so you *can* set the state on page load.

**Comment by EoinShaughnessy** [comment]
Since this issue first came up, we've published [updated guidance](https://design-system.service.gov.uk/components/accordion/#change-how-an-accordion-starts):

> If the user leaves and then returns to the page, the accordion component will remember if sections were opened or closed. You can configure sections to start and stay open, but not stay closed.

@joelanman Does that address your opening comment? Or should we also mention the unique ID?

**Comment by EoinShaughnessy** [comment]
Current wording of Nunjucks `expanded` option:

> Whether the section should be expanded upon initial load or not. Defaults to `false`.

To be clearer, we should probably begin the Description with "Sets whether..."

Also, is this definitely all users have to do to set the state on page load?

**Comment by EoinShaughnessy** [comment]
We've now updated the accordion guidance with [info about session storage behaviour](https://design-system.service.gov.uk/components/accordion/#starting-with-sections-open).
