### ISSUE TITLE
Initial scoping of Hide this Page contribution

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1604]
## What 

We need to scope out what is needed to turn hide this page contribution into a component and let the contributor know so that they can start working on it. 

## Why
Work on Hide this page component is planned for Sprint 5 & 6. There might be things the contributor can start on before the team get involved. This will likely be useful for when we start the work as well. 

## Who needs to know about this
Devs, designers, content

## Done when

- [ ] We have a rough idea of what needs to be done

**Comment by timpaul** [comment]
WORK TO BE DONE:

Clarify guidance on what kind of website to redirect users to 
([based on this feedback](https://github.com/alphagov/govuk-design-system-backlog/issues/213#issuecomment-760180246))

Update button text to make it clearer for screen reader users
([based on this feedback](https://github.com/alphagov/govuk-design-system-backlog/issues/213#issuecomment-780663640))

Consider how to make the component safe to use with voice activation
([based on this feedback](https://github.com/alphagov/govuk-design-system-backlog/issues/213#issuecomment-805296409))

**Comment by timpaul** [comment]
DESIGN RATIONALE:

The button is aligned to the right because this is an emerging convention for this kind of functionality. For that reason we believe that people will look for it there (this does rely in them already being familiar with the concept though).


RESEARCH QUESTIONS:

- Does the left/right alignment of the button affect how many people interact with it?

**Comment by lfdebrux** [comment]
@timpaul I think we might want to clarify in the guidance where exactly in the page template HTML the component(s) should go; it might also be good to code up a full page example for the review app.

**Comment by lfdebrux** [comment]
Another thought, with the visually hidden component, would it be useful/good to have it visible when it is tab-focused? (similar to how the skip link behaves)

**Comment by f-marry** [comment]
Am curious about the size of this button. Any rationale behind this size? Or just the default size?
For something that needs to be hit in a hurry, feels like it should be bigger / easier to hit. (Possibly making the hit areas larger than the visual button if you're worried about visual weight.)

I also wonder how much perception need to be managed about what the button do, to ensure it doesn't given a false sense of security.
Presumably it doesn't "hide this page" from your history, not clear data entered in a form...

**Comment by timpaul** [comment]
IMPLEMENTATION:

- The current implementation contains _two_ blocks of code, which is not something that our current component model supports. We'll need a way to support this, probably using JS injection

> Another thought, with the visually hidden component, would it be useful/good to have it visible when it is tab-focused? (similar to how the skip link behaves)

The hidden element is just text, so not focusable

**Comment by christopherthomasdesign** [comment]
Just writing up my thinking on the points outlined by @timpaul above...

### Clarify guidance on what kind of website to redirect users to

I think the behaviour already described seems a sensible default i.e. opening BBC Weather in a new tab and Google in the previous tab. Because BBC Weather’s a fairly generic, more pictorial site. But it should only be that – a default.

Add extra guidance to say:
* Base the choice of website on what you know about your users.
* Don’t choose anything that could arouse suspicion or put the user in danger e.g. if someone whose first language is not English opens a text-heavy website in English.

### Clarify with guidance and example where on the page the component should go

We should include a full-page example in the guidance, of a simple question page with the button included. Make sure the guidance explains where the component should sit in the HTML.

According to the contribution, the button should be placed just inside the `<main>` section of the page. I think this makes sense, and the visual positioning seems to work relative to the main container. We should take some pages to an accessibility clinic to test that the control makes sense placed there for screen reader users.

I’ve created a [branch of Frontend](https://github.com/alphagov/govuk-frontend/tree/hide-this-page) and placed the component, as-is, into some example pages. The build is failing because I haven’t built out the component properly, but you can test it locally. Will add some findings in a separate comment below.

### Update button text to make it clearer for screen reader users

Some options for this:
* Hide this page [quick exit button, it opens BBC Weather in a new tab] (GOV.UK team’s suggestion)
* Hide this page [and open a new tab]

I think the latter does enough to clarify what’s going to happen?

### Consider how to make the component safe to use with voice activation

I don’t know how to start on this one tbh, a designer and a dev should pair on it.

### Decide whether to keep the escape key functionality

Decision: don’t use the escape key functionality for the first iteration of the component. 

The main reason is that **we can’t be sure that the escape key will work consistently across different contexts**. It could conflict with the behaviour of other UI components within the service, such as modals – that might be ok if handled carefully. But it might also conflict with things outside of the service, like accessibility software or browser extensions. For example, NVDA uses the escape key to ‘exit focus mode’.

We also think it would be easier to add in the future than to remove it if we found that it was causing problems.

This would also mean removing the bit of visually hidden text that’s intended to go at the very top of the page, telling users they can hide the page using the escape key. Which was a bit problematic because it’s technically a separate component...

**Comment by jbuller** [comment]
> Decision: don’t use the escape key functionality for the first iteration of the component.

So. How would a non-voice input, keyboard only user quickly hide the page?
Perhaps a combination of keys could be used instead of Esc alone?

Why does the functionality need to be removed for mobile devices? How about saying in the instructions "on devices with keyboards you can press Shit+Esc"?

**Comment by christopherthomasdesign** [comment]
Hi @jbuller thanks for your comment. Really good point and it's a hard decision to balance. I decided to open it up on the original issue to get more thoughts: https://github.com/alphagov/govuk-design-system-backlog/issues/213#issuecomment-864032416

**Comment by jbuller** [comment]
It also occurs to me that people, with and without visual impairments use mobile devices with a Bluetooth keyboard or braille input/display.
