### ISSUE TITLE
Decide approach for sub-domain consent

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#1613]
## What
Confirm that we can go with the sub-domain approach to gathering consent for cookies across design-system.service.gov.uk and frontend.design-system.service.gov.uk

## Why
The privacy team raised some concerns in an email thread about taking this approach. We think we'll be able to do this, but we need to make it clear in the cookie banner and cookie page, but we should double check.

## Who needs to know about this
Performance Analyst; Product Manager; Developers

## Done when

- [x] Chatted with privacy team about sub-domain consent
- [x] We know what we need in place (from a legal point-of-view) to add sub-domain tracking, e.g: what content we need on the site to explain it to users
- [ ] Relevant cards updated

**Comment by SaraC19** [comment]
Sent Joe Levey an email on 26 April to find out next steps - copied in Vanita and Trang for their reference. Awaiting reply.

**Comment by trang-erskine** [comment]
We got a response back from Joe 

"I've had a look at the proposal and I have a few initial thought: 
On the banner you should allude to the essential cookies as a matter of best practice. i.e. we use essential cookies on this site for blah. We also use analytics cookies help us understand how our website is being used. 

In the cookie policy, I would take the time to explain that we're talking about more than 1 site. Maybe start with a sentence like 'this cookie policy applies to the collection of sites that make up the GOV.UK Design System' including Site A and Site B. And be clear that by consenting to cookies on one domain, it applies to the other domain. 

What data will you be getting out of GA? Will it be clientID level data or aggregate data? For example, this user (clientID) did ABC and then came back 1 week later and did DEF vs 1000 individual users did ABC. If the former, I think it is likely to constitute personal data because the ClientID enables you to distinguish individual users from other users. But I have raised a question with our legal support to confirm / deny this. In the meantime, you can only really call it anonymous if you are doing the latter. " 

@vanitabarrett @SaraC19 @calvin-lau-sig7 It might be worth getting the content right while we have Joe's attention so we have it ready for when we have GA setup for both Design System website and Frontend Docs. The priority for us should be get GA on the Design System website, Frontend Docs can wait. If this is too much of a distraction, we can park this for now. What do you think?

**Comment by vanitabarrett** [comment]
@trang-erskine Got a catch-up next week with Sara, Calvin and myself to talk about the content. I'm going to move this card back to upcoming sprints for now, as I think our main focus will be getting the content for the main design system site, but I'll update this card if we do discuss the changes we'll need to make for sub-domain consent.

**Comment by romaricpascal** [comment]
Looks like GOV.UK Pay is using the same cookie to register consent both on [their main site](https://payments.service.gov.uk) and [their technical documentation](https://docs.payments.service.gov.uk/). It could be worth getting in touch with them about policies and wording (though both sites share the same navigation menu, if not the same layout, which may come into play).
