### ISSUE TITLE
Build cookie consent functions in the design system

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#1614]
## What
Add the cookie consent mechanism to the design system. This will consist of a set of functions to:

- accept and reject cookies
- save consent in a cookie, with an expiry of 1 year
- delete cookies when a user changes their preference to reject
- look up a user's consent
- be able to map a cookie name to it's category, e.g: `_ga` -> `analytics`

**Example in GOV.UK**: https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js

Part of this work will be deciding what the consent cookie looks like, e.g: it's name; what the value will look like

We should be ok to merge these changes as we're adding a set of functions without using them, so they won't have any effect on users yet.

## Why
We will need this set of functions to hook into when we add the cookie banner and cookie preferences form.

## Who needs to know about this
Developers

## Done when

- [ ] We know what the consent cookie will look like
- [ ] We have functions for the main cookie banner/form behaviour, e.g: accepting and rejecting cookies; deleting cookies (see list above)
- [ ] Tests for all of the cookie consent functions

**Comment by lfdebrux** [comment]
Possibly the best (and easiest) way to do this is to "lift and shift" existing code from another project.

I'm looking at two different options:

- [GOV.UK Publishing components' `cookie-functions.js` (mentioned above)](https://github.com/alphagov/govuk_publishing_components/tree/master/app/assets/javascripts/govuk_publishing_components/lib)

**Comment by lfdebrux** [comment]
After looking at the three options above, I've come up with the following feature table:

|                                                                        | [GOV.UK Publishing components](https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/javascripts/govuk_publishing_components/lib/cookie-functions.js) | [Digital Marketplace](https://github.com/alphagov/digitalmarketplace-govuk-frontend/blob/master/src/digitalmarketplace/helpers/cookie/cookie-functions.js) | [PaaS product pages](https://github.com/alphagov/paas-product-pages/blob/main/javascripts/cookie-functions.js) |
| ---------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------- |
| accept and reject cookies?                                             | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| save consent in a cookie, with an expiry of 1 year?                    | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| delete cookies when a user changes their preference to reject?         | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| look up a user's consent?                                              | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| be able to map a cookie name to it's category, e.g: \_ga -> analytics? | Y                                                                                                                                                                              | Y                                                                                                                                                          | N                                                                                                              |
|                                                                        |                                                                                                                                                                                |                                                                                                                                                            |                                                                                                                |
| Has tests?                                                             | Y                                                                                                                                                                              | Y                                                                                                                                                          | N                                                                                                              |
| ES6 module?                                                            | N                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| Has hardcoded stuff?                                                   | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| Includes GTM code?                                                     | N                                                                                                                                                                              | N                                                                                                                                                          | Y                                                                                                              |
| Has cookie categories?                                                 | Y                                                                                                                                                                              | Y                                                                                                                                                          | N                                                                                                              |
| Includes cookie banner code?                                           | N                                                                                                                                                                              | N                                                                                                                                                          | Y                                                                                                              |
| Has cookie settings page code?                                         | N                                                                                                                                                                              | N                                                                                                                                                          | Y                                                                                                              |
| Cookies have versions?                                                 | N                                                                                                                                                                              | N                                                                                                                                                          | N                                                                                                              |
| Can remove consent?                                                    | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| Includes Google Analytics cookies?                                     | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| Includes cross Gov tracking cookies?                                   | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |
| Uses secure cookies?                                                   | Y                                                                                                                                                                              | Y                                                                                                                                                          | Y                                                                                                              |

I think Digital Marketplace's cookie code is the best option to base our own cookie code on, because it has all the functionality of the GOV.UK code, but uses ES6 module syntax.

I was interested by PaaS's cookie code as it has a lot of extra functionality that we will need, but the fact it doesn't do cookie categories meant it was missing key functionality, and in any case we would have needed to change the cookie banner code quite a lot.

I'm now working to add the Digital Marketplace code to a branch of govuk-design-system, hopefully this should be straightforward.

**Comment by lfdebrux** [comment]
PR closing this issue is ready to review, I've moved this ticket to the review column
