### ISSUE TITLE
Possible unclear guidance around validating individual date components

### ISSUE THREAD

**Issue by andymantell** [alphagov/govuk-design-system#1637]
## Related documentation
https://design-system.service.gov.uk/components/date-input/#error-messages

## Suggestion
The above guidance on date field validation says:

> If the date is incomplete
> Highlight the day, month or year field where the information is missing. If more than one field is missing information, highlight the date input as a whole.

If the day and the month are missing but the person has entered a year, should we still be highlighting the whole field? Including the year component which technically doesn't have errors at this point? Or should we be highlighting day and month but not year?

Interpreting this guidance as it's written would result in this:

![image (5)](https://user-images.githubusercontent.com/134642/116410244-7c28ad00-a82c-11eb-8108-a67c2f2e2b77.png)

But I would argue that the following is more logical (Only highlighting the bits that are actually in an error state)

![image (6)](https://user-images.githubusercontent.com/134642/116410260-7f239d80-a82c-11eb-9403-210f5701b1a7.png)

Was there a reason this guidance was written in this way?

**Comment by CharlotteDowns** [comment]
Thank you @andymantell for raising this issue.

If it's ok, I'm just going to capture some of the [conversation on Slack](https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6/p1619614987311000) here too.

> Was there a reason this guidance was written in this way?

A few possible answers from the discussion:

- "I think it was intentional - based on the assumption that it's useful to limit how complex validation rules can get. But if it's helpful for users and doesn't add too much complexity from a dev point of view, it's worth changing."
-  Could the reason to highlight all the fields if more than one of them is incorrect, as a case where correct numbers may be entered into the wrong fields?

I think the consensus from the discussion is that this is a change worth making to the guidance, do you think it would also be good to have a visual example to make it clearer?
