### ISSUE TITLE
Set up process to start scraping GitHub analytics to report on Design System usage

### ISSUE THREAD

**Issue by SaraC19** [alphagov/govuk-design-system#1845]
## What
Create a way of reporting on GitHub analytics for Design System usage. Very similar to another ticket looking at contribution data: https://github.com/alphagov/govuk-design-system/issues/2027

Specifically to look at:

1. How many repos are using the Design System
2. How many times each component in the Design System is being used
3. [Pageviews ](https://docs.github.com/en/rest/reference/pages)of the Design System repo

Frankie Roberto put together an excellent presentation that showcased how we can scrape the data from GitHub to see how users on GitHub are using Design System. 

https://docs.google.com/presentation/d/1-sG1gMPKXWmqVyqhmf8-pEde8AXnpGK7mjOj_ye7tqw/edit

His process:

https://github.com/x-govuk/govuk-frontend-component-stats

## Why
So we can better understand how people are using Design System and monitor it over time. This will also mean we can monitor usage when we launch new things. This data will feed into the centralised KPI dashboard to understand performance over time and help the team prioritise when needed. 

## Who needs to know about this
PA, FD, D

## Done when

- [ ] Reviewed the process Frankie used 
- [ ] Decided how we replicate this for ongoing reporting in the format that is most suitable for us

**Comment by oscarduignan** [comment]
I was looking up something else and I spotted this and since we had done something similar for tax services in HMRC I thought I'd pop a cross link to it https://github.com/hmrc/play-frontend-find-usages#exploring-what-we-find-with-datasette I don't think it is exactly the same, but the screenshot in the README at that link shows how we have used [datasette](https://datasette.io/) to be able to query usages and answer questions / look for (anti-)patterns. We stored the usages for components that we found as json lines which we could then store easily and import into a sqlite db which datasette gave us a nice interface for then exploring

**Comment by trang-erskine** [comment]
Close for now. Reopen if we still want to do this.
