### ISSUE TITLE
Publish iterated community backlog

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1958]
## What
Publish iterated community backlog following testing.

## Why
So it's clearer to users which stage a contribution is at and how they can get involved.

## Who needs to work on this
Designers

## Who needs to review this
Designers, Content Designer

## Done when
- [x] Updated any relevant documentation or content (internal and public)
- [x] Documented our decisions
- [ ] Published community backlog
- [ ] Communicated to users changes we have made

**Comment by christopherthomasdesign** [comment]
Things we found in research that we want to address at this stage:
* All participants were confused about ‘waiting to be published’ – particularly why it was before 'actively working on'
* Some users were confused by the fact that some columns are prioritised, some aren’t
* Varied interpretations of ‘needs development’
* One participant thought the project board was something only for the Design System team, to manage work

**Comment by christopherthomasdesign** [comment]
Kicked off on 8 Dec w @calvin-lau-sig7 

#### All participants were confused about ‘waiting to be published’ – particularly why it was before ‘actively working on’

- “Waiting to be worked on?”
- Maybe explain the work the DS team needs to do to get ready to publish – AT testing, detailed tweaks, accessibility testing, writing tests etc.
- Friction: contributions are personal, whilst contribution process is more project-y
- Are the team comfortable with us being open about not being able to work on things?

#### Some users were confused by the fact that some columns are prioritised, some aren’t

- Just leave as current ordering – i.e. mostly in the order the items were added to the column
- Could add tags/labels to issues to reinforce their status on the backlog – but then will have to change as something moves across the board...
- Prioritised hasn’t been ‘officially’ done for a long time — but informally done for other things... remove the ‘prioritised’ section column for now until we've run a prioritisation process
- But float the prioritised ones to the top
- Do people actually work on what we want them to work on?

#### Varied interpretations of ‘needs development’

- Confusion with work that developers do, rather than something broader
- Describe what happens between 2 WG review stages – what needs to happen before next stage?
- Ideas: ready for next review, “fully developed”

#### One participant thought the project board was something only for the Design System team, to manage work

- Create a better entry point into the GitHub ‘layer’ – review backlog page content
- Content does good job of saying what the purpose is, but doesn’t prepare you for how to use the project board
- Prepare the user for a project board

**Comment by calvin-lau-sig7** [comment]
To help us talk around, I've committed a [draft edit of the Backlog 'lead-in' page into the project board](https://github.com/alphagov/govuk-design-system/pull/1950/commits/5433374e18a85b5baeb32edbfa60edd079c80a0e).
