### ISSUE TITLE
Design System Website doesn't load in IE8

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#2051]
## Description of the issue

The GOV.UK Design System Website doesn't load in IE8 when using Browserstack.

https://user-images.githubusercontent.com/1590604/152381147-5635cef0-a319-43f1-a45c-6d5af173d2ab.mov

**Comment by timpaul** [comment]
We're pretty sure it’s the CloudFront distribution. The origin works (https://govuk-design-system-preview.netlify.app/) as does https://govuk-design-system-preview.netlify.app/

**Comment by 36degrees** [comment]
The user who raised this issue was attempting to see how the accordion worked in IE8.

We're reasonably sure that the Design System worked in IE8 on Windows 7 until recently.

Specifically, we think that it has stopped working because of a change to the security policy associated with the CloudFront distribution, which was [updated from TLSv1.2_2019 to TLSv1.2_2021](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html) on December 1 2021 – as far as we can tell this removed support for the few remaining ciphers that work in IE8 on Windows 7.

However, looking at our analytics data, there were zero sessions recorded from IE8 in all of 2021. Note that this data only includes users who opt in to accept cookies.

On that basis, at the minute we have no plans to change the security policy to re-enable support for IE8. However, we're going to keep an eye on this and see if this comes up again.

**Comment by 36degrees** [comment]
Closing as the Design System website no longer supports IE8.
