### ISSUE TITLE
Investigate platform options for Design System Day 2022

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2165]
## What
Agree which platforms we will use for video, note taking and collaboration activities.

## Why
So we can set expectations with attendees and facilitators, and secure budget approval if needed.

## Done when
- [x] Investigated options
- [x] Platform agreed for video
- [x] Platform agreed for note taking
- [x] Platform agreed for collaboration
- [x] Get access to a Padlet account - @kellylee-gds 
- [x] Check Zoom setup/settings/features/how it works

**Comment by vanitabarrett** [comment]
Notes: https://docs.google.com/document/d/13AFfVkdYhI_ADl6xbBahyHogeUXjxz5noF699pOQXXw/edit#

**Comment by vanitabarrett** [comment]
We've agreed to use the following:

- Zoom, for video conferencing
- Padlet, for collaboration
- Google Docs, for notes

[Full research notes here](https://docs.google.com/document/d/13AFfVkdYhI_ADl6xbBahyHogeUXjxz5noF699pOQXXw/edit#)

@NoraGDS has also [drafted some comms for people running sessions and for participants](https://docs.google.com/document/d/13AFfVkdYhI_ADl6xbBahyHogeUXjxz5noF699pOQXXw/edit#heading=h.veq5h9s5gq0b) to explain what tools we're using and give them an opportunity to flag any issues they might have using or accessing those platforms. If we get a high volume of replies stating people can't access/use something, we can look into it.

We've also decided on Padlet as the most accessible option for collaboration tools. As no sessions have been agreed yet, we'd like session organisers to try and fit the format of their sessions to work within these agreed tools first.

**Comment by vanitabarrett** [comment]
Have added a couple of additional tasks to the 'Done when' criteria for this card:

- Get access to a paid Zoom account - @vanitabarrett
- Get access to a Padlet account - @kellylee-gds
- Make sure team/organisers/volunteers are familiar with and can access Zoom, Padlet and Google Docs
- Draft up some instructions on how to use Padlet (for attendees)
- Configure Zoom account/meeting settings, e.g: live captioning, breakout rooms, hosts/co-hosts

**Comment by ImranH-GDS** [comment]
@vanitabarrett happy to have a chat about it with the group? I've used some of these platforms before and they have some advantages. I believe some of the platforms may have accessibility statements, which I will try to dig out.

With us extending our timescales, and now having @davidc-gds on the team; it might be worth spending a week or so considering the options?

**Comment by vanitabarrett** [comment]
@ImranH-GDS Yep, sounds like a good plan 👍

**Comment by vanitabarrett** [comment]
@ImranH-GDS @davidc-gds and I had a chat today about conference platforms. In short, we think going with a lo-fi version using just Zoom for video conferencing might be simpler for now. We're wary of introducing another 'wrapper' which abstracts things away and might make technical problem solving more tricky.

In terms of Zoom, we also had a chat about the limitations of using the GDS account (primarily, having someone else who needs to join and give you host access; and being unable to have multiple concurrent meetings). Zoom is setup so that you can only have 1 (on some licenses, 2) meetings running at the same time. So if we wanted 7 concurrent sessions, we would need 7 licenses.

Looking at https://zoom.us/pricing, we could get the Pro plan (up to 9 licenses) or the Small Business plan (starting at 10 licenses) for a month, although Imran mentioned that having our own Zoom would be useful for other sessions throughout the year too. We'd need to buy an add-on to increase attendee limits to 500 for at least one license and use that for the keynote. This would allow us to have multiple workshops running at the same time, and each one could have it's own breakout rooms.

Next steps:

- [ ] Chat to @kellylee-gds about getting Zoom (and decide on monthly or yearly)
- [ ] Decide how we distribute Zoom links and passwords to attendees
- [ ] Decide how it works with external participants running workshops (making them host vs having someone from our team in the room as host vs sharing the host key)

**Comment by vanitabarrett** [comment]
### Zoom Meetings

9 pro licenses at £11.99 a month/license =  £107.91 + large meetings add-on (500) for one license at £40 = £147.91 

10 business licenses at £15.99 a month/license = £159.90 + large meetings add-on (500) for one license at £40 = £199.90

If we wanted a Pro Zoom account for a whole year - £119 for 1 license for a year (100 participants)
If we wanted a Business Zoom account for a whole year - £159.90 for 1 license for a year (300 participants)
Large meeting add-ons are always on a monthly basis and would be ~£480 for a year, so I’d recommend only adding it on for a monthly license rather than the yearly one as I don’t think we’d use it that much and it’d significantly increase costs.

### Zoom Events

Sounds like this is an add-on, so you still need Zoom Meetings and this is extra cost. Probably not worth it if that’s the case, at least not for this year. Maybe something to consider if/when we want to explore conference platforms for future Design System Day(s)

**Comment by vanitabarrett** [comment]
Zoom costs document: https://docs.google.com/document/d/1Reqk6WD6mXqGgZjsLkr5yMWHTbEaSI93YeFoGbSet7U/edit#

**Comment by vanitabarrett** [comment]
Writing up some separate tickets for this as it's turning into a bit of an epic. I think we've done the investigation side of this and decided on the platforms, so what's left is actually get spend approval and making setting up the tools/making sure people can access them and understand them

**Comment by vanitabarrett** [comment]
Rest of the work tracked in the following issues:

- https://github.com/alphagov/govuk-design-system/issues/2215
- https://github.com/alphagov/govuk-design-system/issues/2216
- https://github.com/alphagov/govuk-design-system/issues/2217
- https://github.com/alphagov/govuk-design-system/issues/2218
