### ISSUE TITLE
Purchase merchandise and swag for Design System Day 2022

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2293]
## What
Order merchandise and swag for the event.

## Why
So attendees can take something away from the event. 

## Who needs to work on this
Chris (design), Kelly (purchase method)

## Who needs to review this
Imran (budget confirmation)

## Done when
- [x] We know the best purchase method to use
- [x] Design has been finalised
- [x] Merch and swag ordered
- [x] Distribution arranged

**Comment by kellylee-gds** [comment]
@christopherthomasdesign I spoke to the programme today about this, we just need to contact PSO office who will sort it

**Comment by CharlotteDowns** [comment]
Stickers, a5 flyers and notebooks have been ordered.

Swag/Ship/Hack have received the stickers and a5 flyers. Notebooks are due to arrive today (Tuesday 13 September).

The a5 flyer has the September day printed on it, stickers and notebooks are good to go as is.

**Actions**

- [ ] Correct artwork for a5 flyer with new event date (or date removed)
- [ ] Order new a5 flyers and have them sent to Swag/Ship/Hack
- [ ] Make a decision on what we do with flyers with the incorrect date
- [ ] Confirm with Swag/Ship/Hack whether they can hold our items until the new shipping date

**Comment by CharlotteDowns** [comment]
**Decisions**

- Create artwork for a5 flyers without a date and confirm approval for extra spend
- Swag/Ship/Hack have been asked to hold onto the stickers and notebooks till mid November and to dispose of the flyers with the incorrect date
