### ISSUE TITLE
Unnecessary vocalisation of "Copy code" after copy

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#2342]
## Description of the issue

After copying a code example using the "Copy code" button, its label switches to "Code copied", announced to screen readers thanks to the `aria-live="assertive"` on the button. After a while, it returns to its default state, but because of the `aria-live` attribute, "Copy code" gets announced:
- potentially interrupting other announcements if the user moved focus, because the live region is `assertive`
- or just doubling up Voice Over announcing the change of accessible name, which can be annoying.

## Actual vs expected behaviour

At the minimum, there shouldn't be any announcement when "Code copied" disappears from the screen to be replaced by "Copy code".  We may also want to revisit the level of the live region, does it really need to be "assertive"?

I've only tested with Voice Over in Safari, though. It may be that that announcement is useful for other screen readers.

## Potential solution

A potential solution could be to separate the live-region from the button altogether. Displaying the feedback out of the button may have implications for users of magnifiers, though, where the feedback may fall outside of the area they're viewing (then disappear automatically after a time).

## Environment (where applicable)

- Operating system: MacOS 12.5.1
- Browser: Safari + VoiceOver
- Browser version: 15.6.1

**Comment by querkmachine** [comment]
Weirdly the closing comment didn't take, but #3080 implements an improved solution which separates the screen reader announcements into a visually-hidden span. The button changing back to read "Copy code" should now only be heard if the user's focus is still on the button when it changes back.

The announcement is still `assertive` on the basis that a user probably wants immediate feedback that clicking the button has performed the intended action; feedback that a non-sighted user will not receive otherwise. 

This solution is a little imperfect, as we still change the text of the button for visual users, and some (but not all) screen readers will announce both this change and the status span change—however this seemingly isn't a problem in practice (the `assertive` span immediately cancels the button text change announcement) and is preferable to some SRs not making any announcement.
