### ISSUE TITLE
Validate the current draft of Images guidance with W3C approach

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2629]
## What
Current draft version of iterated Images guidance needs validating with WC3 approach. Also plan to gather feedback from users after publishing by using and explaining the experimental tag.

## Why
- Build confidence that this is a sensible approach
- Make sure we’re ready to respond to support queries that may arise post-publishing

## Who needs to work on this
Calvin, David

## Who needs to review this
Charlotte

## Done when
- [x] Complete and send preview PR of current draft to team
- [x] Gather feedback from team
- [x] Decide on needed revisions
- [x] Implement edits into preview

**Comment by calvin-lau-sig7** [comment]
I've now updated the PR https://github.com/alphagov/govuk-design-system/pull/2059 with the latest edits.

Changes:
- Reworked 'Images of text' section to align more with WAI approach — this means structuring guidance to be more about "how you use text in images to give information" rather than "here's some different categories of image text, and what to about them"
- applied suggestions from accessibility experts @davidc-gds and @selfthinker, mostly to add more context
- suggestions also included some minor edits in the "illustration" sections

Be good to see if the "more WAI-aligned" approach works for us. Personally, the advice is starting to feel more sensible.

**Comment by calvin-lau-sig7** [comment]
Thanks all, this is complete. 

We've settled on an approach that explains images that can link to W3C's pages, but not exactly aligned though. Which is okay.
