### ISSUE TITLE
Use the same version of `marked` in our build and our plugins

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-design-system#2767]
## What
Sync `marked` version/source across:

`@metalsmith/markdown`
`lib/extract-page-headings`
`lib/get-macro-options`
`lib/marked-renderer`

## Why
`@metalsmith/markdown` uses `marked` v4+ under the hood, and this does the heavy lifting of rendering our markdown code to HTML.

However, we also directly depend on `marked` for some of our plugins which we use to define custom renderers and lexers.

Recently, [dependabot tried to bump this direct dependency](https://github.com/alphagov/govuk-design-system/pull/2766) to the new v5, which resulted in a swathe of deprecation warnings for the `mangled` and `headerIds` options.

### mangled
We set `mangled` to `false` via `@metalsmith/markdown`, but not in our plugins, so even though we don't need mangling in these plugins, we were still deprecation warnings because we hadn't explicitly disabled it.

### headerIds
We use this property to generate ids for our headings. I looked into use the plugin `marked` recommends instead, but it generated ESM-related errors: https://github.com/markedjs/marked-gfm-heading-id/issues/310

We want to avoid getting warnings or errors like these that only apply to one part of the build process.

## Who needs to work on this
Developer

## Who needs to review this
Developer

## Done when

- [ ] Our marked plugins and `@metalsmith/markdown` use the same version of `marked`
- [ ] We have a way to keep these in-sync (preferably by having each of the relevant modules use the same source `marked`)

**Comment by webketje** [comment]
Since v1.9.0 `@metalsmith/markdown` provides a `render` option which you could use to force using a locally installed marked version: https://github.com/metalsmith/markdown#using-another-markdown-library. 
Since v1.8.0 the options have moved to `engineOptions`, see https://github.com/metalsmith/markdown/releases/tag/v1.8.0 (this warning is logged when `metalsmith.env('DEBUG')` contains `@metalsmith/markdown*`)

I may consider making `marked` an (optional) peerDependency in the future due to the complications of their switch to extensions vs options (tracked in https://github.com/metalsmith/markdown/issues/70)

**Comment by colinrotherham** [comment]
Just a note to say `marked@8.0.0` has been released so deprecated options have been removed

* https://github.com/alphagov/govuk-frontend/pull/4165
* https://github.com/alphagov/govuk-design-system/pull/3123

## Breaking changes

Heading IDs from Metalsmith's `marked@4.3.0` are removed in **DesignSystemRenderer()** using `marked@8.0.0`

We've seen this before, since in https://github.com/alphagov/govuk-design-system/pull/3002/commits/21787a8a593b5487d1ba0a64aed58edbb7cc8c5f we noted that [jstransformer-marked](https://www.npmjs.com/package/jstransformer-marked) still needed `{ smartypants: true }` but elsewhere the option was logging deprecation warnings so needed [marked-smartypants](https://www.npmjs.com/package/marked-smartypants) instead

Using the [suggestion above](https://github.com/alphagov/govuk-design-system/issues/2767#issuecomment-1590203001) though we could bypass Metalsmith's `marked@4.3.0` rendering with:

```js
const markdown = require('@metalsmith/markdown')
const { Marked } = require('marked')

// Use `marked@8.0.0`
const marked = new Marked()

metalsmith.use(
  markdown({

    // Bypass `marked@4.3.0`
    render(source) {
      return marked.parse(source)
    }
  })
)
```

## Deprecated options removed

The renderer bypass would need to use the following packages instead of options:

* `smartypants: true` → [marked-smartypants](https://www.npmjs.com/package/marked-smartypants)
* `headerIds: true` → [marked-gfm-heading-id](https://www.npmjs.com/package/marked-gfm-heading-id)
* `highlight` → [marked-highlight](https://www.npmjs.com/package/marked-highlight)

Since the previous options have now been removed (see [known extensions](https://marked.js.org/using_advanced#extensions) list)

**Comment by colinrotherham** [comment]
Turns out `{ renderer: DesignSystemRenderer() }` _does_ override by design

From the documentation:

> ### [The Marked Pipeline](https://marked.js.org/using_pro#use)
>For example, using `marked.use({renderer})` would modify a render, whereas `marked.use({extenstions: [{renderer}]})` would add a new renderer.

But handling tokens (not strings) with [named `extensions`](https://marked.js.org/using_pro#custom-extensions-example) lets each one keep their own new renderer:

* https://github.com/alphagov/govuk-design-system/pull/3130

Ready for review

**Comment by 36degrees** [comment]
Looks like this is done 🎉
