### ISSUE TITLE
Explore adding a button to Exit this Page component guidance for teams to inform us when they have used it

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2849]
## What
Add a button to the guidance where teams are encouraged to share their service name, department and consent to contact for further research.

Mvp button could be 'We have used this component".

Also consider whether the button is needed on both the component guidance and pattern, or just the component guidance.

## Why
To help us track where EtP is being used and set up further conversations.

## Who needs to work on this
TBC - need further info from the team before decision reached.

## Who needs to review this
TBC

## Done when
- [ ] Considered whether the button is needed on both the component guidance and pattern
- [x] We know how the button will ask and collect data
- [x] We know how to ask for user's consent
- [x] We know how we will safely store data in accordance to privacy guidelines
- [ ] Prototyped a button
- [ ] Reviewed
- [ ] Added to component guidance [and pattern]

**Comment by stevenjmesser** [comment]
There's a couple of options for how this could work. What feels simplest and closer to a complete solution (to me) is to hand the user off to a styled SmartSurvey, which handles data storage and privacy notices, reducing the amount of work to do with Information Assurance. It also allows us to include a question asking which components and patterns are used on a service, meaning we collect more information through one form; if a form was embedded on each component or pattern page instead, that's a lot of forms to fill in!

We might also want to collect service name, organisation name and a contact email address to help with de-duplicating submissions too. Collecting the email address allows us to screen out spam submissions too. (We can suggest that mailbox is used instead of a person's email address, though both are fine.)

I've had other thoughts of how this would feed into better collecting data on usage of the design system, so would love to chat that through with anyone involved in this. It shouldn't widen the scope but will make sure all the work aligns and the data can be analysed.

**Comment by calvin-lau-sig7** [comment]
Summary of what I reckon how the links for #2848 and #2849 will look on the component and pattern pages:

On the ‘Help improve this component/pattern section’, replace the link to the backlog issue page [(example)](https://github.com/alphagov/govuk-design-system-backlog/issues/1) to a new GitHub discussion category [(example)](https://github.com/alphagov/govuk-design-system-backlog/discussions/categories/prioritised-components-and-patterns) page.
- Discussion category will be the main space for users to discuss Exit this page and for the team to make announcements, making use of the discussion features
- Backlog issue page will probably still be needed for consistency and findability for people browsing the backlog repo, but will be locked down and with text redirect users to the discussion category. This is to reduce duplication and confusion on where to go.

In the same section, also add a button to a survey or form tool
- Survey or form will collect info about their implementation of Exit this Page, also service name, organisation, contact email, and questions asking which other components and patterns the use.

**Comment by stevenjmesser** [comment]
Personally I’m agnostic as to whether it needs to be a button, happy to go with whatever a designer recommends.

**Comment by owenatgov** [comment]
Weighing in:

I think a SmartSurvey link is fine. Is there anything we need to think about re: branding or is this already handled? I remember Vanita doing some work years ago on branding SmartSurvey using govuk-frontend.

The changes to 'Help improve xyx' will require some dev work as this partial is currently quite rigid. I don't anticipate this being a challenge, we just need to think about how to extend it so that it doesn't break other components and how they pass data to it. We have the option to update how all our pages use that partial fairly easily though so whilst there's a light unknown, it's not a major concern.

**Comment by stevenjmesser** [comment]
Sounds great, thanks for your thoughts, @owenatgov. 

SmartSurvey is all branded up, yes (or it was when I checked earlier in the year, can't imagine it will have changed).

**Comment by stevenjmesser** [comment]
Here's a couple of sketches/scrappy prototypes based on @owenatgov's hardcoded approach. The content is bad, would definitely need @calvin-lau-sig7's help with that! 

![image](https://github.com/alphagov/govuk-design-system/assets/23193154/8210fc43-211c-403b-8166-4e3a8c8844f2)

![image](https://github.com/alphagov/govuk-design-system/assets/23193154/10ef950f-f634-4fb6-9318-171e1fac5c57)

The link opens a SmartSurvey, e.g. https://surveys.publishing.service.gov.uk/s/preview/JQ7GLT/699DFE6BB168F2E0B7E9A5440B8B50

**Comment by kellylee-gds** [comment]
Looks great!

**Comment by stevenjmesser** [comment]
Here's a survey I threw together https://surveys.publishing.service.gov.uk/s/preview/MPR0MV/9901FD8DF46ED73D593D58630D2660

**Comment by stevenjmesser** [comment]
Published survey here: https://surveys.publishing.service.gov.uk/s/MPR0MV/

**Comment by stevenjmesser** [comment]
@calvin-lau-sig7 added a commit for this to the guidance PR: https://github.com/alphagov/govuk-design-system/pull/2721/commits/f189d5d7b69b8fd6755062e3b771c34d7f2da494
