### ISSUE TITLE
More options for font weight override classes.

### ISSUE THREAD

**Issue by AlexBeesley** [alphagov/govuk-design-system#2873]
## Feature request
I'd like to see additional override classes for font weight, rather than just for regular and bold, for example I expected this to already exist: `govuk-!-font-weight-600` - ideally classes for all commonly used weights from 100 and 900 etc.

## Context
I am building a form for The Pensions Regulator, we use [this](https://github.com/gunndabad/govuk-frontend-aspnetcore) as a starting point and have built extensions to use that work within Umbraco.

## Alternatives
I could do my own custom CSS, but I think this should be built in.

**Comment by querkmachine** [comment]
Hi @AlexBeesley,

The version of Transport that is used with GOV.UK Frontend is only available in regular and bold weights, which is why we only provide override classes for those weights. It wouldn't make sense for us to ship additional weight classes in Frontend when they wouldn't be functional for the majority of our users.

If you're using a typeface that isn't GDS Transport, we would expect you to add any additional classes you need to your project's code.

I'm going to close this issue for now as this seems like a change we're unlikely to make at this time, but feel free to continue the discussion and provide more context as to why additional weight options might be useful for your service.

**Comment by AlexBeesley** [comment]
Thank you for the explanation @querkmachine,

We are using the Transport typeface for this project, but there was some confusion as our .govuk-link was given a font-weight of 600 in our extensions project, which caused me some confusion. After some analysis, this is not an issue with the govuk frontend controls, apologies. 

(I also realise this was the wrong place for this, should have posted this in [alphagov/govuk-frontend](https://github.com/alphagov/govuk-frontend))
