### ISSUE TITLE
Add pre-commit linting 

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3047]
## What

Add [husky](https://typicode.github.io/husky) and [lint-staged](https://github.com/okonet/lint-staged) to automatically format files affected by [the linting we run on CI](https://github.com/alphagov/govuk-design-system/blob/main/.github/workflows/test.yaml#L82-L94). 

For reference, the GOV.UK Frontend provides a good structure for the implementation with:
 - [a set up of these tools in two steps](https://github.com/alphagov/govuk-frontend/pull/2848/commits): first lint-staged, then husky
 - [linting scripts split between the command (`:cli`) and the run on the files](https://github.com/alphagov/govuk-frontend/blob/main/package.json#L37-L45)
 - [a neat structure to reuse commands that affect multiple types of files in `.lintstagedrc`](https://github.com/alphagov/govuk-frontend/blob/main/.lintstagedrc.js#L3-L24)

## Why

With the addition of [Prettier and EditorConfig checks](https://github.com/alphagov/govuk-design-system/pull/2997), [CI may fail on files not being formatted properly](https://github.com/alphagov/govuk-design-system/actions/runs/5833884971/job/15822280183?pr=3046), which is annoying when commiting content changes.

This is probably equally annoying for JS and SCSS files, though because our editors are likely configured to format/lint on save, affects us less.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] Content is linted automatically pre-commit

**Comment by frankieroberto** [comment]
One alternative (or possibly an addition) you could consider is to do auto-fixing of code style issues within a GitHub Workflow action.

I’ve done this in a few places. The basic process is to add a workflow which runs the linters/checkers in auto-fix mode on any  commits associated with a pull request, then commit and push any changes (if there are any), and then re-run the linters/checkers to catch any issues that aren't auto-fixable so that the status is reported correctly. See [an example](https://github.com/DFE-Digital/bat-design-history/blob/main/.github/workflows/lint.yml).

The advantages of doing this way:

* avoids people seeing confusing errors if they’re using a git GUI and the linters aren't installed or don't work for some reason (mainly applies to non-developers)
* will still work if people use the GitHub website to suggest a change (which happens a fair bit for the Design System website as it's mainly content)

The disadvantages:

* you end up with extra git commits, which you may want to squash before merging (easier if you routinely squash-merge via GitHub anyway)
* I’ve not (yet) found a way to make this work with PRs opened from a fork - currently it fails as there’s no permission to push commits a branch in someone’s fork. I think this may be resolvable if people tick the "allow maintainers to push" checkbox, but I'm not sure how.
