### ISSUE TITLE
Implement redirects for Netlify equivalent to our current NGINX config

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3322]
## What

Add [a configuration file for redirects on Netlify](https://docs.netlify.com/routing/redirects/redirect-options/) that reproduces the redirects we currently have set up in [our NGINX configuration](https://github.com/alphagov/govuk-design-system/blob/main/deploy/nginx.conf).

## Why

We'll need these redirects in place when deployed to Netlify

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Our Netlify previews (like https://govuk-design-system-preview.netlify.app/) have the same redirects as the live site.

**Comment by 36degrees** [comment]
I've reviewed the location rules we have in our current nginx config:

https://github.com/alphagov/govuk-design-system/blob/e2ec59808e88a8514821f272b7678e1a2e288e06/deploy/nginx.conf#L149-L158

Covered by #3336 

https://github.com/alphagov/govuk-design-system/blob/e2ec59808e88a8514821f272b7678e1a2e288e06/deploy/nginx.conf#L160-L176

Covered by #3337 

https://github.com/alphagov/govuk-design-system/blob/e2ec59808e88a8514821f272b7678e1a2e288e06/deploy/nginx.conf#L178-L183

I think this is intended to guard against e.g. leaking `.env` files that might be present when building the site, possibly copied from somewhere else? Not convinced it's needed.

https://github.com/alphagov/govuk-design-system/blob/e2ec59808e88a8514821f272b7678e1a2e288e06/deploy/nginx.conf#L185-L189

The smoke tests that are referenced run when we're deploying to PaaS, and are only required because of the way we guard the 'non-canonical' cloudapps.digital domain via basic auth – it won't be needed in a post-PaaS world.
