### ISSUE TITLE
Review hybrid Password component decision using Text Input with before/after content

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3479]
Decide what will be built for the Password Input component, and how it fits in with other component parts.

Includes: Review putting toggle button in template (vs JavaScript)

## Done when

- [ ] Thing to do

**Comment by querkmachine** [comment]
Given the changes since made to the main branch to make components easier to extend (e.g. #4567, #4742), we're now more comfortable having the Password input component inherit the Input component, rather than implementing it as a separate entity. 

This approach was spiked in #4741 and #4746, where we validated that this approach would be practical.
