### ISSUE TITLE
Confirmation pattern - the title should probably be an H1

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#413]
On a confirmation page the title is currently and H2 - it should probably be an H1

https://design-system.service.gov.uk/patterns/confirmation-pages/default/index.html

**Comment by dashouse** [comment]
I think we should certainly make the change so it's an`<h1>` by default but make it configurable, either to allow for an `<h2>` if desired or perhaps using the same `isPageHeading: true` logic as the `<legend>` and `<label>`? 

For example, I believe DVLA use a confirmation panel with an `<h2>` because the panel is preceded by the vehicles registration mark as the `<h1>`

**Comment by nickcolley** [comment]
`titleLevel: 2` default (1)?

**Comment by igloosi** [comment]
updated in https://github.com/alphagov/govuk-design-system/pull/439
