### ISSUE TITLE
Code examples in code blocks have shrunk

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#531]
The size of the text in the code blocks also appear to have shrunk somewhat… (comparing to https://deploy-preview-519--govuk-design-system-preview.netlify.com/components/checkboxes/, which hasn't been rebased)

<img width="1352" alt="screen shot 2018-09-10 at 16 58 06bst" src="https://user-images.githubusercontent.com/121939/45309054-c3968980-b51a-11e8-8e29-777dc46a11e3.png">

<img width="1352" alt="screen shot 2018-09-10 at 16 58 15bst" src="https://user-images.githubusercontent.com/121939/45309086-d315d280-b51a-11e8-92f4-5eb0f5b57303.png">

**Comment by 36degrees** [comment]
I think this is because the browser's default font size for monospaced fonts is 13px rather than 16px, but the rem calculation is based on the default font size being 16px.

Not sure what the best thing to do is here… maybe not use rem for monospaced elements?

**Comment by 36degrees** [comment]
Unsurprisingly, this is also affecting inline code:

<img width="752" alt="screen shot 2018-09-10 at 17 15 15bst" src="https://user-images.githubusercontent.com/121939/45310049-2c7f0100-b51d-11e8-864b-3dfa547256c0.png">
<img width="748" alt="screen shot 2018-09-10 at 17 15 25bst" src="https://user-images.githubusercontent.com/121939/45310050-2c7f0100-b51d-11e8-9958-6208c07bec18.png">

**Comment by nickcolley** [comment]
I did some investigation using this page: https://cbracco.github.io/html5-test-page/

Looks like inputs with a type that is not 'text' also change size, but may not be a problem for us, will check.

**Comment by nickcolley** [comment]
Interesting article shared by Ollie: https://manishearth.github.io/blog/2017/08/10/font-size-an-unexpectedly-complex-css-property/

"Another way of looking at it is whenever the font family or language changes, you should recompute the font-size as if the language and family were always that way up the tree."

My mental model of REM is "a unit sized relative to the root element" which I thought was the the HTML elements.

Turns out it's actually "a unit sized to relative to the root element, which can change if the font family is monospace" 😱 

"I think the reason behind this is that monospace fonts tend to be wider, so the default font size (medium) is scaled so that they have similar widths, and all other keyword font sizes get shifted as well."
