### ISSUE TITLE
Wrong checkbox clicked in labels example

### ISSUE THREAD

**Issue by DebsDee** [alphagov/govuk-design-system#661]
Wrong checkbox ticked when a same named label below is clicked (behaviour viewed in chrome). These are the example checkboxes in the labels 'How to guide'.
&nbsp;
&nbsp;
![screencast-design-system service gov uk-2018 12 04-15-4](https://user-images.githubusercontent.com/7225720/49454433-0942b580-f7dd-11e8-992e-4ea0f8b672cd.gif)

**Comment by nickcolley** [comment]
I think this is because `idPrefix` and `name` are duplicated in these examples.

We'll need to change the second example to something different, for example 'checkbox-2'

Each of these files require changes:

- https://github.com/alphagov/govuk-design-system/blob/master/src/get-started/labels-legends-headings/legend-m-s/index.njk#L41-L42
- https://github.com/alphagov/govuk-design-system/blob/master/src/get-started/labels-legends-headings/legend-h1/index.njk#L41-L42
- https://github.com/alphagov/govuk-design-system/blob/master/src/get-started/labels-legends-headings/legend-h1/index.njk#L41-L42
- https://github.com/alphagov/govuk-design-system/blob/master/src/get-started/labels-legends-headings/label-m-s/index.njk#L30-L31
- https://github.com/alphagov/govuk-design-system/blob/master/src/get-started/labels-legends-headings/label-h1/index.njk#L30-L31

**Comment by DebsDee** [comment]
@nickcolley Hey sure, I'll create a PR.

**Comment by dashouse** [comment]
Great spot @DebsDee, totally missed that 💯
