### ISSUE TITLE
Default heading sizes and guidance

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#698]
I feel like the default heading size used for h1s can be overly large - particularly where we're using one-thing-per page with a single field.

[Postcode example](https://design-system.service.gov.uk/patterns/question-pages/postcode/index.html):
<img width="736" alt="screenshot 2019-01-15 at 12 16 57" src="https://user-images.githubusercontent.com/2204224/51181708-c687f900-18c3-11e9-886d-27fcdf65d036.png">

To me the heading is out of proportion with the page. It also forces the main question to break on to two lines, which I'd normally want to avoid for legibility.

Longer pages (content pages?) may warrant a larger heading, or where there's other fields on the page - but in this scenario, it doesn't feel correct. 

If I were designing this page without the design system, I'd use `govuk-heading-l` / 36px for most in-service pages. On passports all but our start / intro pages used this size.

The [headings section](https://design-system.service.gov.uk/styles/typography/#headings) of the design system includes examples of each size, but no mention of what's appropriate or not. Failing it being mentioned there, I think services are likely to use what's used in the examples in the design system - which all seem to use `xl`.

My suggested actions:
* Add guidance to the headings section of the design system on type sizes - even if the answer is that services should choose something appropriate.
* Reduce the heading size on example pages where it's deemed to be too large (most question pages?).
* Depending on the above, update templates as needed - eg prototype kit.

**Comment by stevenaproctor** [comment]
@edwardhorsford I agree that the `xl` is can feel a little shouty at times. Any guidance should mention choosing heading structure should be consistent. It is odd when the size and heading hierarchy changes from one page to the next.

**Comment by nickcolley** [comment]
Just to note that GOV.UK Publishing changes the title of their headings depending on on the circumstance.

Here's the code for the 'document collection' format: https://github.com/alphagov/government-frontend/blob/master/app/views/content_items/document_collection.html.erb#L9

Which is using the following variant of their title component:
https://govuk-publishing-components.herokuapp.com/component-guide/title/long_title_with_context

**Comment by chrisadesign** [comment]
Just adding another example as I brought this up on Slack.  We've got some fairly long questions in our service and xl feels a bit much so thinking of dropping to l across the service. 

<img width="992" alt="image" src="https://user-images.githubusercontent.com/22620603/53864197-c5319d80-3fe3-11e9-9d3d-0d5e77b904d0.png">

**Comment by joelanman** [comment]
@chrisadesign this is one of the main reasons I'd use a smaller heading size for question pages - also the lack of balance between very large question text and small answer text.

**Comment by dashouse** [comment]
From an end goal perspective, the current examples container is not as full featured as we might like. One of the original designs allowed the user to configure their own version of each component. By including something like this the default example would appear less strict.

I cannot find the original design but I have a small unstyled prototype which shows some basic functionality:
 
![configure-component](https://user-images.githubusercontent.com/23356842/54608708-34c67480-4a49-11e9-9fb5-8aee0068e5b8.gif)

@nickcolley Made an awesome version of something like this too where you could edit the HTML or Nunjucks directly to create your example before copying it.

Regarding the current state of things, there's some really good points made here. Some of the original constraints we had around this decision are no longer issues. For example, when this decision was made, we were considering a prose-scope / markdown container that could work with components inside and it was important to try and retain the `<h1>` = `govuk-heading-xl`, `<h2` = `govuk-heading-l` relationship in some way.

I'm going to set aside some time to look into this and see if it makes sense to bump everything in a  service down one level or see how changing size based page type feels.

**Comment by StephenGill** [comment]
I *think* this is covered by the recent update to headings guidance: https://design-system.service.gov.uk/styles/typography/#headings - but feel free to re-open if you disagree.

**Comment by edwardhorsford** [comment]
@StephenGill I don't think it is covered.

We're continuing to see services with headings that are out of proportion with the rest of the content - likely because all the examples use `xl`.

Nearly all the existing examples still use `xl` - which is generally too large for most pages.

If question pages aren't meant to default to `xl`, then the examples shouldn't use that as a default. If they _are_ meant to default to that, I'd love to know some more context around that decision.

**Comment by edwardhorsford** [comment]
@StephenGill I'm unable to reopen this issue.

**Comment by joelanman** [comment]
this is related to https://github.com/alphagov/govuk-design-system/issues/1021

**Comment by christopherthomasdesign** [comment]
I had a look through the examples that use `govuk-heading-xl` as the default heading size. I did this manually 😂which was good for actually looking at them all but means I may have missed the odd one...

Layouts:
* [Two-thirds column layout](https://design-system.service.gov.uk/styles/layout/common-two-thirds/index.html)
* [Two-thirds/one-third layout](https://design-system.service.gov.uk/styles/layout/common-two-thirds-one-third/index.html)
* [2 rows layout](https://design-system.service.gov.uk/styles/layout/common-two-thirds-two-thirds-one-third/index.html)
 
Templates:
* [Default page template](https://design-system.service.gov.uk/styles/page-template/default/index.html)
* [Customised page template](https://design-system.service.gov.uk/styles/page-template/custom/index.html)

Components:
* [Checkboxes](https://design-system.service.gov.uk/components/checkboxes/default/index.html)
* [Checkboxes with hints](https://design-system.service.gov.uk/components/checkboxes/hint/index.html)
* [Checkboxes with conditional reveal](https://design-system.service.gov.uk/components/checkboxes/conditional-reveal/index.html)
* [Checkboxes with error message](https://design-system.service.gov.uk/components/checkboxes/error/index.html)
* [Date input](https://design-system.service.gov.uk/components/date-input/default/index.html)
* [Date input with autocomplete](https://design-system.service.gov.uk/components/date-input/date-of-birth/index.html)
* [Date input with error message](https://design-system.service.gov.uk/components/date-input/error/index.html)
* [Error message](https://design-system.service.gov.uk/components/error-message/default/index.html)
* [Error message with legend](https://design-system.service.gov.uk/components/error-message/legend/index.html)
* [Error summary with links](https://design-system.service.gov.uk/components/error-summary/linking/index.html)
* [Error summary with links to multiple fields](https://design-system.service.gov.uk/components/error-summary/linking-multiple-fields/index.html)
* [Error summary with radios or checkboxes](https://design-system.service.gov.uk/components/error-summary/linking-checkboxes-radios/index.html)
* [Error summary full page example](https://design-system.service.gov.uk/components/error-summary/full-page-example/index.html)
* [Fieldset address group](https://design-system.service.gov.uk/components/fieldset/address-group/index.html)
* [Fieldset legend as page heading](https://design-system.service.gov.uk/components/fieldset/default/index.html)
* [Panel](https://design-system.service.gov.uk/components/panel/default/index.html)
* [Radios](https://design-system.service.gov.uk/components/radios/default/index.html)
* [Radios stacked](https://design-system.service.gov.uk/components/radios/stacked/index.html)
* [Radios with hints](https://design-system.service.gov.uk/components/radios/hint/index.html)
* [Radios with text divider](https://design-system.service.gov.uk/components/radios/divider/index.html)
* [Radios with conditional reveal](https://design-system.service.gov.uk/components/radios/conditional-reveal/index.html)
* [Radios with error message](https://design-system.service.gov.uk/components/radios/error/index.html)

Patterns:
* [Address](https://design-system.service.gov.uk/patterns/addresses/multiple/index.html)
* [Bank details](https://design-system.service.gov.uk/patterns/bank-details/default/index.html)
* [Bank details with branching](https://design-system.service.gov.uk/patterns/bank-details/branch/index.html)
* [Dates](https://design-system.service.gov.uk/patterns/dates/default/index.html)
* [Memorable dates](https://design-system.service.gov.uk/patterns/dates/memorable-date/index.html)
* [Dates with error message](https://design-system.service.gov.uk/patterns/dates/error/index.html)
* [Ethnic groups](https://design-system.service.gov.uk/patterns/ethnic-group/default/index.html)
* [Ethnic groups detailed question](https://design-system.service.gov.uk/patterns/ethnic-group/black/index.html)
* [Ethnic groups with error message](https://design-system.service.gov.uk/patterns/ethnic-group/error/index.html)
* [Check answers](https://design-system.service.gov.uk/patterns/check-answers/default/index.html)
* [Confirmation pages](https://design-system.service.gov.uk/patterns/confirmation-pages/default/index.html)
* [Page not found pages](https://design-system.service.gov.uk/patterns/page-not-found-pages/default/index.html)
* [There is a problem with the service pages](https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/default/index.html)
* [Question pages](https://design-system.service.gov.uk/patterns/question-pages/default/index.html)
* [Question pages with passport details](https://design-system.service.gov.uk/patterns/question-pages/passport/index.html)
* [Question pages with legend as heading](https://design-system.service.gov.uk/patterns/question-pages/date-of-birth/index.html)
* [Question pages with label as heading](https://design-system.service.gov.uk/patterns/question-pages/postcode/index.html)
* [Question pages with caption](https://design-system.service.gov.uk/patterns/question-pages/section-headings/index.html)
* [Question pages with progress indicator](https://design-system.service.gov.uk/patterns/question-pages/progress/index.html)
* [Service unavailable pages](https://design-system.service.gov.uk/patterns/service-unavailable-pages/default/index.html)
* [Service unavailable pages, generic](https://design-system.service.gov.uk/patterns/service-unavailable-pages/general/index.html)
* [Service unavailable pages with known date](https://design-system.service.gov.uk/patterns/service-unavailable-pages/available-at-known-date/index.html)
* [Service unavailable pages with link to another service](https://design-system.service.gov.uk/patterns/service-unavailable-pages/link-to-another-service/index.html)
* [Service unavailable pages after service closes](https://design-system.service.gov.uk/patterns/service-unavailable-pages/after-service-closes/index.html)
* [Service unavailable pages before a service opens](https://design-system.service.gov.uk/patterns/service-unavailable-pages/before-service-opens/index.html)
* [Service unavailable pages with no replacement service](https://design-system.service.gov.uk/patterns/service-unavailable-pages/no-replacement-service/index.html)
* [Service unavailable pages with a replacement service](https://design-system.service.gov.uk/patterns/service-unavailable-pages/service-replaced/index.html)
* [Start pages](https://design-system.service.gov.uk/patterns/start-pages/default/index.html)

We'd need to think a bit about when to use different heading sizes in examples. It seems a lot neater to just use `xl` by default and help users understand when to change it, because a lot of these examples are devoid of context. However, I appreciate that most of the questions / form fields are shown as they would be if they were the only question on a page. Interestingly, we use a `l` size on one of the [ethnic groups questions](https://design-system.service.gov.uk/patterns/ethnic-group/black/index.html) but don't mention why.

**Comment by terrysimpson99** [comment]
There's a related inconsistency in the examples that could be fixed as part of this. The examples use three different styles: (1) the field label is h1 (such as 'date input'); (2) the field label is not h1 and is bold (such as 'payment card details'); (3) the field label is not h1 and is non-bold (such as 'bank details'). Different designers unaware of the inconsistency draw may be applying bold when it's not necessary depending on which example they use.

**Comment by kellylee-gds** [comment]
Discussed at triage about considering the following comment from the backlog in this work https://github.com/alphagov/govuk-design-system-backlog/issues/64#issuecomment-604535397 @christopherthomasdesign
