### ISSUE TITLE
Consider presenting examples of components with common attributes

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-design-system#707]
While we do not want to apply attributes to most of our component examples it may be worth including an example of how to apply common attributes such as `required` and `checked` in specific examples.

For example:

### Making inputs required

You can add a required attribute by...

```
      {{ govukInput({
        label: {
          text: "Full name"
        },
        id: "name",
        name: "name",
        attributes: {
          required: true
        }
      }) }}
```

(This came from Zen Desk ticket)

**Comment by querkmachine** [comment]
This may have been resolved over time. I'm not confident of the state of things back when this issue was raised, but today we tend to have multiple examples of components in use on pages, including coded examples of checked checkboxes and radio buttons.

[Our guidance on validation](https://design-system.service.gov.uk/patterns/validation/#turn-off-html5-validation) recommends not using the `required` attribute, so we probably wouldn't have examples of this in use to align with that. 

Feel free to comment and reopen if there's something I've missed.
