### ISSUE TITLE
Query on diagram of template areas

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#802]
I *think* there may be a mistake in [this diagram of the template areas](https://design-system.service.gov.uk/styles/page-template/block-areas/index.html).

In the text on the [page templates page](https://design-system.service.gov.uk/styles/page-template/#blocks) it states that `beforeContent` sits outside of main. It also states that `main` overrides main.

In the below diagram, `beforeContent` is shown as being within the `main` override. Based on the text, I think it should be outside it - that `main` wraps `content` only.
![screenshot 2019-02-21 at 12 07 50](https://user-images.githubusercontent.com/2204224/53168086-bf928b80-35d1-11e9-9400-e6f71f462e95.png)

**Comment by hannalaakso** [comment]
@edwardhorsford Thanks for raising this. The confusion is caused by two similarly named elements: `block:main` in the template macro and `<main>` in the HTML.

You can either use:
1. `block:beforeContent`(which sets content outside `<main>` element) and `block:content`(which is wrapped within `<main>`)
2. `block:main` that overrides both `block:beforeContent` and `<main>`

So the documentation and the diagram are correct but it's true that the naming could cause some confusion. From an implementation point of view, it made sense calling the template element `block:main` as it overrides `block:beforeContent` but maybe less so from a markup point of view. To fix this, we could rename `block:main` to `block:supersede` or some such. However we would anticipate this being a breaking change for many of our users so we need to balance the inconvenience caused by making such a change against the benefits gained.

**Comment by joelanman** [comment]
Yeh just to note I find this confusing too

**Comment by edwardhorsford** [comment]
Thanks @hannalaakso.

Based on what you've said, I think the text "Override the default <main> element." is either incorrect or could do with further clarification. It sounds like it _also_ supersedes `block:beforeContent`.

**Comment by nickcolley** [comment]
We've updated the wording based on your feedback, if you run into any more issues in the future feel free to re-open this or raise a new issue thanks Ed :)

**Comment by edwardhorsford** [comment]
Thanks @nickcolley, that covers my confusion.
