### ISSUE TITLE
Consider adding a layout example for header with service name.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#826]
I feel like the current example headers in the layout section do not cover the majority use case, which is GOV.UK together with a service name.

The current examples:
<img width="778" alt="Screenshot 2019-03-14 at 11 01 24" src="https://user-images.githubusercontent.com/2204224/54351938-943b1380-4648-11e9-8b5c-f3832747968b.png">
<img width="953" alt="Screenshot 2019-03-14 at 11 01 29" src="https://user-images.githubusercontent.com/2204224/54351943-969d6d80-4648-11e9-9781-e546dd1ba6cf.png">

From my experience assessing services, the most common example is:
<img width="872" alt="Screenshot 2019-03-14 at 11 02 31" src="https://user-images.githubusercontent.com/2204224/54352075-b2a10f00-4648-11e9-9428-cf2684d85180.png">

---

I'd like to add the above example because:
* We should have examples of the most common use case
* To use as a 'reference implementation' when services are testing their layout.

I feel like the example without a service name comes from a time when we used to recommend services avoid having a name. Is this still the case?

FWIW In practice I don't think many services are using a navigation style like the one in the example.

**Comment by 36degrees** [comment]
Hi Ed,

> I feel like the current example headers in the layout section do not cover the majority use case, which is GOV.UK together with a service name.

We have an example of the header with a service name on the [header component page](https://design-system.service.gov.uk/components/header/).

> I'd like to add the above example because:
>
> - We should have examples of the most common use case
> - To use as a 'reference implementation' when services are testing their layout.

The primary need for the [page template](https://design-system.service.gov.uk/styles/page-template/) page (which I'm assuming you're referring to) is to help people understand _what's possible_ when using the page template in their application.

To do this, we provide two examples:

1) What you get when you extend the template by 'default', passing just the absolute minimum (which is why the service name is absent)
2) A more comprehensive 'kitchen sink' example which shows how to add _everything_ that could be found on a page, including service names and navigation, content for the `beforeContent` block (the phase banner), and navigation in the footer.

So:

> I feel like the example without a service name comes from a time when we used to recommend services avoid having a name. Is this still the case?

We're just showing what you get with the absolute minimum.

> FWIW In practice I don't think many services are using a navigation style like the one in the example.

We need (somewhere) to show everything that's possible.

If we were going to make any changes, it'd be good to understand what issues you're seeing and what you mean by a 'reference implementation'?

Thanks,

Ollie

**Comment by aliuk2012** [comment]
Hi @edwardhorsford,

We believe that @36degrees has answered your question. As you have not posted anything further for over two weeks we consider this issue resolved and will close it.

If this is not the case, please feel free to re-open this issue.
