### ISSUE TITLE
Searches without relevant results can return results

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-design-system#940]
This issue is from a May 2019 external accessibility audit report.

**WCAG Reference**: Usability feedback
**Issue ID**: DAC_4
**URL**: All pages

## Summary
When entering a search such as 'search box', there are no results for search box since it does not exist, but there are results for things like checkboxes.

> “I inputted the search term ‘Search box’ into the autocomplete. Although options appeared on the page it was not indicated to me that my term was not available which could be confusing. This occurred using JAWS, NVDA and VoiceOver for iPhone and Mac.

## Screenshot
<img width="351" alt="" src="https://user-images.githubusercontent.com/2445413/60201947-74b7a780-9841-11e9-8620-c6886622a59f.png">

**Comment by 36degrees** [comment]
This happens because the individual terms are `OR`'ed together – so the search being performed in the example screenshot is `Search OR box`.

This is perhaps counter-intuitive to user's expectations – it seems reasonable that entering more terms makes the search more restrictive, and so you would see less results.

If we chose instead to `AND` the individual terms together, entering any term that was not present in a result would return nothing. For example, searches for 'small checkboxes', 'green panel' or 'password input' would not show any results. We could offset some of this by adding aliases for common terms, but it would be impossible to come up with an exhaustive list.

Results are scored as to how well they match the search terms provided. We could explore hiding results below a certain threshold, but that threshold would be hard to define and verify – without a _lot_ of data about how different search terms perform (i.e. what is minimum threshold of results that actually get clicked) we'd basically have to guess. If we had a larger corpus or more search activity this might be possible, but it's non-trivial.

I'm going to close this, but we should keep an eye out in user research to see if it causes users problems.
